name: Build Project

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        run: dotnet restore TelecomWeb/TelecomWeb.sln

      - name: Build
        run: dotnet build --configuration Release TelecomWeb/TelecomWeb.sln
